# Generated by Django 4.0.1 on 2022-01-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='username',
            new_name='name',
        ),
    ]
